name: Robot Framework Tests

on:
  push:
    branches:
      - main  # Executa o pipeline ao fazer push para a branch main
  pull_request:
    branches:
      - main  # Executa ao criar um PR para a branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu

    steps:
      # 1. Faz checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Usa a versão mais recente do Python 3

      # 3. Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Instala o Chrome e o ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+')
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 5. Executa os testes
      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results testes.robot

      # 6. Publica os resultados como artefatos
      - name: Upload test results
        if: always()  # Executa mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/